import { useEffect, useState } from 'react';
import PageHeader from '../components/PageHeader';
import Notice from '../components/Notice';
import { siteApi } from '../services/api';

export function About() { return <><PageHeader title="About Saileela Mandal Palkhi">Devotion, participation and seva, presented with verified information.</PageHeader><section className="section"><div className="shell split"><div><h2>Verified history</h2><p className="muted">Official details to be updated.</p></div><Notice title="Content safety"><>Sai-related publications and Shirdi institutions are not presented as Saileela Mandal history or management.</></Notice></div></section></>; }
export function Schedule() { return <><PageHeader title="Palkhi / Yatra">Routes, dates and halt information will be published after official confirmation.</PageHeader><section className="section"><div className="shell"><Notice title="Route information pending">Official dates, locations, distance and live status are not currently available.</Notice></div></section></>; }
export function Gallery() { const [items, setItems] = useState([]); useEffect(() => { siteApi.content().then(({ data }) => setItems(data.gallery || [])).catch(() => {}); }, []); return <><PageHeader title="Saileela Gallery">Only verified Saileela photographs will be displayed.</PageHeader><section className="section"><div className="shell">{items.length ? <div className="gallery">{items.map((item) => <figure key={item._id}><img src={item.imagePath} alt={item.altText || item.title}/><figcaption>{item.title}</figcaption></figure>)}</div> : <Notice title="Official gallery pending">Legacy festival imagery has been removed and no unverified photographs are presented as Saileela content.</Notice>}</div></section></>; }
export function Seva() { return <><PageHeader title="Seva">Support categories and activities will be shown after official verification.</PageHeader><section className="section"><div className="shell cards"><div className="card"><span>SEVA</span><h3>Saileela Seva</h3><p>Official details to be updated.</p></div></div></section></>; }
export function Committee() { return <><PageHeader title="Committee">Only verified Saileela committee information will be published.</PageHeader><section className="section"><div className="shell"><Notice>External Sai or Shirdi publication committees are not used as Saileela Mandal committee data.</Notice></div></section></>; }
