import { useState } from 'react';
import { dbtApi, enquiryApi, registrationApi } from '../services/api';
import PageHeader from '../components/PageHeader';
import Notice from '../components/Notice';

function FormShell({ title, children, onSubmit, status }) { return <><PageHeader title={title}/><section className="section"><div className="shell form-card"><form onSubmit={onSubmit}>{children}<button className="button primary" type="submit">Submit</button>{status && <p className="form-status">{status}</p>}</form></div></section></>; }
const Field = ({ label, name, type = 'text', required = false }) => <label className="field"><span>{label}</span><input name={name} type={type} required={required}/></label>;
export function Registration() { const [status, setStatus] = useState(''); async function submit(event) { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); data.consent = true; try { const { data: result } = await registrationApi.create(data); setStatus(`Registration ${result.registration.registrationNumber} created. Pass: ${result.pass.passNumber}`); } catch (error) { setStatus(error.response?.data?.message || 'Registration failed.'); } } return <FormShell title="Palkhi Registration" onSubmit={submit} status={status}><div className="form-grid"><Field label="Full name" name="fullName" required/><Field label="Mobile number" name="phone" required/><Field label="Email" name="email" type="email"/><Field label="Emergency contact" name="emergencyContact"/><Field label="Address" name="address"/><Field label="Blood group" name="bloodGroup"/></div><p className="muted">Registration details are stored securely for pass verification. Official yatra dates are not assumed.</p></FormShell>; }
export function VerifyPass() { const [result, setResult] = useState(null); async function submit(event) { event.preventDefault(); const number = new FormData(event.currentTarget).get('passNumber'); try { const response = await registrationApi.verify(number); setResult(response.data); } catch (error) { setResult({ message: error.response?.data?.message || 'Pass not found.' }); } } return <><PageHeader title="Verify Pass"/><section className="section"><div className="shell form-card"><form onSubmit={submit}><Field label="Pass number" name="passNumber" required/><button className="button primary" type="submit">Verify</button></form>{result && <div className="notice"><strong>{result.success ? result.pass.registration.fullName : 'Verification result'}</strong><p>{result.success ? result.pass.passNumber : result.message}</p></div>}</div></section></>; }
export function Contact() { const [status, setStatus] = useState(''); async function submit(event) { event.preventDefault(); try { await enquiryApi.contact(Object.fromEntries(new FormData(event.currentTarget))); setStatus('Message received.'); } catch (error) { setStatus(error.response?.data?.message || 'Could not send message.'); } } return <FormShell title="Contact Saileela Mandal" onSubmit={submit} status={status}><div className="form-grid"><Field label="Name" name="name" required/><Field label="Mobile" name="phone" required/><Field label="Email" name="email" type="email"/><label className="field full"><span>Message</span><textarea name="message" required/></label></div></FormShell>; }
export function Advertisement() { const [status, setStatus] = useState(''); async function submit(event) { event.preventDefault(); try { await enquiryApi.advertisement(Object.fromEntries(new FormData(event.currentTarget))); setStatus('Enquiry received.'); } catch (error) { setStatus(error.response?.data?.message || 'Could not send enquiry.'); } } return <><PageHeader title="Partnership enquiry">No verified sponsorship rate card is configured.</PageHeader><section className="section"><div className="shell"><Notice/><div className="form-card"><form onSubmit={submit}><div className="form-grid"><Field label="Name" name="name" required/><Field label="Mobile" name="phone" required/><Field label="Email" name="email" type="email"/><label className="field full"><span>Message</span><textarea name="message"/></label></div><button className="button primary">Send enquiry</button><p>{status}</p></form></div></div></section></>; }
export function DBT() { const [status, setStatus] = useState(''); async function submit(event) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await dbtApi.submit(form); setStatus('Receipt submitted for review.'); } catch (error) { setStatus(error.response?.data?.message || 'Upload failed.'); } } return <><PageHeader title="Direct bank transfer">Official bank details are not configured for public display.</PageHeader><section className="section"><div className="shell"><Notice>Do not transfer funds using bank details from old documents.</Notice><div className="form-card"><form onSubmit={submit} encType="multipart/form-data"><div className="form-grid"><Field label="Donor name" name="donorName" required/><Field label="Mobile" name="phone" required/><Field label="Email" name="email" type="email"/><Field label="Amount" name="amount" type="number" required/><Field label="Transaction reference" name="transactionReference" required/><label className="field"><span>Proof</span><input name="proof" type="file" accept=".jpg,.jpeg,.png,.pdf" required/></label></div><button className="button primary">Upload receipt</button><p>{status}</p></form></div></div></section></>; }
export function Tshirt() { return <><PageHeader title="Merchandise">No verified Saileela merchandise catalogue is configured.</PageHeader><section className="section"><div className="shell"><Notice>Old products, pricing and pickup instructions have been removed until an official catalogue is supplied.</Notice></div></section></>; }
